Substituted ioreg for lspci on OS X and added system_profiler output

diff --git a/explorer b/explorer
--- a/explorer
+++ b/explorer
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Name:         explorer
-# Version:      0.0.6
+# Version:      0.0.8
 # Release:      1
 # License:      CC-BA (Creative Commons By Attribution)
 #               http://creativecommons.org/licenses/by/4.0/legalcode
@@ -16,7 +16,7 @@
 #               Designed to be an expanded and modernised version of
 #               Linux Explorer by Joe Santoro of Unix Consultants
 
- MYVERSION="0.0.6"                                #
+ MYVERSION="0.0.8"                                #
    LICENSE="CC-BA"                                #
  COPYRIGHT="Richard Spindler"                     #
     MYDATE="$(date +'%Y.%m.%d.%m.%H.%M')"         # Date and time now
@@ -36,7 +36,7 @@ KEEPFILES="0"                                     # Default to remove files crea
  CODENAME="LINUXexplo"
 unset GZIP                                        # Ensure that GZIP is unset for later use.
 
-if [ "$OSNAME" == "Darwin" ]; then
+if [ "$OSNAME" == "Darwin" ] ; then
   HOSTID=$(netstat -I en0 |grep en0 | awk '{print $4}' |head -1)   
 else
   HOSTID=$(/usr/bin/hostid)                      
@@ -428,6 +428,8 @@ mywhich() {
   local mypath=$(which $command 2>/dev/null)
   if [  "$mypath" =  "" ] ; then
     echo "Command $command not found" >> $NOTFNDLOG
+    echo $1
+    exit
     echo "NOT_FOUND"
   elif [ ! -x "$mypath" ] ; then
     echo "Command $command not executable" >> $NOTFNDLOG
@@ -489,7 +491,6 @@ findCmds() {
             SLEEP=$(mywhich sleep               )
         SYSTEMCTL=$(mywhich systemctl           )
             MOUNT=$(mywhich mount               )
-           MD5SUM=$(mywhich md5sum              )
                MV=$(mywhich mv                  )
               SAR=$(mywhich sar                 )
              SORT=$(mywhich sort                )
@@ -641,7 +642,6 @@ findCmds() {
               ARP=$(mywhich arp                 )
   # Tuning
            IOSTAT=$(mywhich iostat              )
-           VMSTAT=$(mywhich vmstat              )
              IPCS=$(mywhich ipcs                )
          MODPROBE=$(mywhich modprobe            )
            DEPMOD=$(mywhich depmod              )
@@ -659,6 +659,15 @@ findCmds() {
            DOCKER=$(mywhich docker              )
   # Gentoo
         RC_UPDATE=$(mywhich rc-update           )
+  if [ "$OSNAME" == "Darwin" ] ; then
+           VMSTAT=$(mywhich vm_stat             )
+           MD5SUM=$(mywhich md5                 )
+            IOREG=$(mywhich ioreg               )
+  SYSTEM_PROFILER=$(mywhich system_profiler     )
+  else 
+           VMSTAT=$(mywhich vmstat              )
+           MD5SUM=$(mywhich md5sum              )
+  fi
 }
 
 ##############################################################################
@@ -752,93 +761,110 @@ netbackup() {
 
 hardware_checks() {
   Echo "Section - Hardware Info"
-  if [ -x $CARDCTL ] ; then
-    $CARDCTL info     > ${LOGDIR}/sysconfig/cardctl-info.out 2>&1
-    $CARDCTL status   > ${LOGDIR}/sysconfig/cardctl-status.out 2>&1
-    # $CARDCTL ident    > ${LOGDIR}/sysconfig/cardctl-ident.out 2>&1
+  if [ -x $IOREG ] ; then
+    $IOREG -ailtf                 > ${LOGDIR}/sysconfig/ioreg_-ailtf.out          2>&1
+    $IOREG -iltf                  > ${LOGDIR}/sysconfig/ioreg_-iltf.out           2>&1
   fi
-  if [ -x $LSPCI ] ; then
-    $LSPCI          > ${LOGDIR}/sysconfig/lspci.out     2>&1
-    $LSPCI -n       > ${LOGDIR}/sysconfig/lspci-n.out   2>&1
-    $LSPCI -knn     > ${LOGDIR}/sysconfig/lspci-knn.out 2>&1
-    $LSPCI  | while read line ; do
-      Bus=$(/bin/echo $line 2>/dev/null | awk '{ print $1 }')
-      $LSPCI -vv -s $Bus > ${LOGDIR}/sysconfig/lspci_-vv_-s_${Bus}.out 2>&1
-    done
+  if [ -x $SYSTEM_PROFILER ] ; then
+    $SYSTEM_PROFILER              > ${LOGDIR}/sysconfig/system_profiler.out       2>&1
   fi
-  # Get the port names from the HDA cards
-  for i in /sys/class/scsi_host/host*/device/fc_host\:host*/port_name ; do
-    if [ -f $i ] ; then
-      name=$( echo $i | sed 's/\//_/g' | sed 's/^_//g')
-      echo "Port Name : $(cat $i )" >> ${LOGDIR}/sysconfig/cat_${name}.out 2>&1
+  if [ "$OSNAME" == "Darwin" ] ; then
+    $SYSCTL machdep.cpu           > ${LOGDIR}/sysconfig/proc_cpuinfo.out          2>&1
+    $SYSCTL machdep.memmap        > ${LOGDIR}/sysconfig/proc_meminfo.out          2>&1
+    $SYSCTL vfs                   > ${LOGDIR}/sysconfig/proc_filesystems.out      2>&1
+    $FDISK -a hfs /dev/rdisk0     > ${LOGDIR}/sysconfig/proc_partitions.out       2>&1
+     physicalCPUs=$( $SYSCTL machdep.cpu.brand_string | $WC -l                    )
+         cpuCores=$( $SYSCTL machdep.cpu.core_count | $AWK '{print $2}'           )
+    cpuProcessors=$( $SYSCTL sysctl machdep.cpu.thread_count | $AWK '{print $2}'  )
+  else
+    if [ -x $CARDCTL ] ; then
+      $CARDCTL info     > ${LOGDIR}/sysconfig/cardctl-info.out 2>&1
+      $CARDCTL status   > ${LOGDIR}/sysconfig/cardctl-status.out 2>&1
+      # $CARDCTL ident    > ${LOGDIR}/sysconfig/cardctl-ident.out 2>&1
     fi
-  done
-  # Get a listing of the /dev directory
-  MakeDir ${LOGDIR}/dev
-  $LS -laR /dev  > ${LOGDIR}/dev/ls_-laR_dev.out
-  if [ -x "$LSUSB" ] ; then
-    $LSUSB -xv > ${LOGDIR}/sysconfig/lsusb_-xv.out 2>&1
-    $LSUSB -tv > ${LOGDIR}/sysconfig/lsusb_-tv.out 2>&1
-  fi
-  if [ -x "$LSDEV" ] ; then
-    $LSDEV -type adaptor > ${LOGDIR}/sysconfig/lsdev_-type_adaptor.out 2>&1
-  fi
-  if [ -x "$ACPI" ] ; then
-    $ACPI -V > ${LOGDIR}/sysconfig/acpi-V.out 2>&1
-  fi
-  if [ -x $FREE ] ; then
-    $FREE    > ${LOGDIR}/sysconfig/free.out
-    $FREE -k > ${LOGDIR}/sysconfig/free_-k.out
-  fi
-  $LS -laR /dev > ${LOGDIR}/sysconfig/ls-laR_dev.out
-  if [ -d /udev ] ; then
-    $LS -laR /udev > ${LOGDIR}/sysconfig/ls-laR_udev.out
-  fi
-  # Global Devices list
-  if [ -x "$LSHAL" ] ; then
-    $LSHAL  > ${LOGDIR}/sysconfig/lshal.out
-  fi
-  if [ -x /usr/share/rhn/up2date_client/hardware.py ] ; then
-    /usr/share/rhn/up2date_client/hardware.py > ${LOGDIR}/sysconfig/hardware.py.out 2>&1
-  fi
-  if [ -x "$SMARTCTL" ] ; then
-    for device in $( $LS /dev/[a-z]d[a-z] /dev/st[0-9] /dev/sg[0-9]  2> /dev/null) ; do
-      name=$( echo $device | sed 's/\//_/g' )
-      ${SMARTCTL} -a $device 2>/dev/null 1> ${LOGDIR}/sysconfig/smartctl-a_${name}.out
+    if [ -x $LSPCI ] ; then
+      $LSPCI          > ${LOGDIR}/sysconfig/lspci.out     2>&1
+      $LSPCI -n       > ${LOGDIR}/sysconfig/lspci-n.out   2>&1
+      $LSPCI -knn     > ${LOGDIR}/sysconfig/lspci-knn.out 2>&1
+      $LSPCI  | while read line ; do
+        Bus=$(/bin/echo $line 2>/dev/null | awk '{ print $1 }')
+        $LSPCI -vv -s $Bus > ${LOGDIR}/sysconfig/lspci_-vv_-s_${Bus}.out 2>&1
+      done
+    fi
+    # Get the port names from the HDA cards
+    for i in /sys/class/scsi_host/host*/device/fc_host\:host*/port_name ; do
+      if [ -f $i ] ; then
+        name=$( echo $i | sed 's/\//_/g' | sed 's/^_//g')
+        echo "Port Name : $(cat $i )" >> ${LOGDIR}/sysconfig/cat_${name}.out 2>&1
+      fi
     done
+    # Get a listing of the /dev directory
+    MakeDir ${LOGDIR}/dev
+    $LS -laR /dev  > ${LOGDIR}/dev/ls_-laR_dev.out
+    if [ -x "$LSUSB" ] ; then
+      $LSUSB -xv > ${LOGDIR}/sysconfig/lsusb_-xv.out 2>&1
+      $LSUSB -tv > ${LOGDIR}/sysconfig/lsusb_-tv.out 2>&1
+    fi
+    if [ -x "$LSDEV" ] ; then
+      $LSDEV -type adaptor > ${LOGDIR}/sysconfig/lsdev_-type_adaptor.out 2>&1
+    fi
+    if [ -x "$ACPI" ] ; then
+      $ACPI -V > ${LOGDIR}/sysconfig/acpi-V.out 2>&1
+    fi
+    if [ -x $FREE ] ; then
+      $FREE    > ${LOGDIR}/sysconfig/free.out
+      $FREE -k > ${LOGDIR}/sysconfig/free_-k.out
+    fi
+    $LS -laR /dev > ${LOGDIR}/sysconfig/ls-laR_dev.out
+    if [ -d /udev ] ; then
+      $LS -laR /udev > ${LOGDIR}/sysconfig/ls-laR_udev.out
+    fi
+    # Global Devices list
+    if [ -x "$LSHAL" ] ; then
+      $LSHAL  > ${LOGDIR}/sysconfig/lshal.out
+    fi
+    if [ -x /usr/share/rhn/up2date_client/hardware.py ] ; then
+      /usr/share/rhn/up2date_client/hardware.py > ${LOGDIR}/sysconfig/hardware.py.out 2>&1
+    fi
+    if [ -x "$SMARTCTL" ] ; then
+      for device in $( $LS /dev/[a-z]d[a-z] /dev/st[0-9] /dev/sg[0-9]  2> /dev/null) ; do
+        name=$( echo $device | sed 's/\//_/g' )
+        ${SMARTCTL} -a $device 2>/dev/null 1> ${LOGDIR}/sysconfig/smartctl-a_${name}.out
+      done
+    fi
+    ##############################################################################
+    # Collect Hardware information from the hwinfo program if installed
+    ##############################################################################
+    if [ -x $HWINFO ] ; then
+      $HWINFO                       > ${LOGDIR}/sysconfig/hwinfo.out                 2>&1
+      $HWINFO  --isapnp             > ${LOGDIR}/sysconfig/hwinfo_--isapnp.out        2>&1
+      $HWINFO  --scsi               > ${LOGDIR}/sysconfig/hwinfo_--scsi.out          2>&1
+      $HWINFO  --framebuffer        > ${LOGDIR}/sysconfig/hwinfo_--framebuffer.out   2>&1
+    fi
+    if [ -x "$PROCINFO"  ] ; then
+      $PROCINFO  > ${LOGDIR}/sysconfig/procinfo.out 2>&1
+    fi
+    if [ -x "$DMIDECODE" ] ; then
+      $DMIDECODE  > ${LOGDIR}/sysconfig/dmidecode.out 2>&1
+    fi
+    if [ -x $LSHW  ] ; then
+      $LSHW > ${LOGDIR}/sysconfig/lshw.out 2>&1
+    fi
+    $CAT /proc/cpuinfo            > ${LOGDIR}/sysconfig/proc_cpuinfo.out          2>&1
+    $CAT /proc/meminfo            > ${LOGDIR}/sysconfig/proc_meminfo.out          2>&1
+    $CAT /proc/mdstat             > ${LOGDIR}/sysconfig/proc_mdstat.out           2>&1
+    $CAT /proc/interrupts         > ${LOGDIR}/sysconfig/proc_interrupts.out       2>&1
+    $CAT /proc/filesystem         > ${LOGDIR}/sysconfig/proc_filesystems.out      2>&1
+    $CAT /proc/devices            > ${LOGDIR}/sysconfig/proc_devices.out          2>&1
+    $CAT /proc/iomem              > ${LOGDIR}/sysconfig/proc_iomem.out            2>&1
+    $CAT /proc/ioports            > ${LOGDIR}/sysconfig/proc_ioports.out          2>&1
+    $CAT /proc/partitions         > ${LOGDIR}/sysconfig/proc_partitions.out       2>&1
+    $CAT /proc/slabinfo           > ${LOGDIR}/sysconfig/proc_slabinfo.out         2>&1
+    $CAT /proc/softirqs           > ${LOGDIR}/sysconfig/proc_softirqs.out         2>&1
+     physicalCPUs=$( $CAT /proc/cpuinfo | grep "physical id" | $SORT | $UNIQ | $WC -l )
+         cpuCores=$( $CAT /proc/cpuinfo | grep "cpu cores"  | $UNIQ  )
+    cpuProcessors=$( $CAT /proc/cpuinfo | grep "^processor" | $UNIQ  )
   fi
-  ##############################################################################
-  # Collect Hardware information from the hwinfo program if installed
-  ##############################################################################
-  if [ -x $HWINFO ] ; then
-    $HWINFO                 > ${LOGDIR}/sysconfig/hwinfo.out                 2>&1
-    $HWINFO  --isapnp       > ${LOGDIR}/sysconfig/hwinfo_--isapnp.out        2>&1
-    $HWINFO  --scsi         > ${LOGDIR}/sysconfig/hwinfo_--scsi.out          2>&1
-    $HWINFO  --framebuffer  > ${LOGDIR}/sysconfig/hwinfo_--framebuffer.out   2>&1
-  fi
-  if [ -x "$PROCINFO"  ] ; then
-    $PROCINFO  > ${LOGDIR}/sysconfig/procinfo.out 2>&1
-  fi
-  if [ -x "$DMIDECODE" ] ; then
-    $DMIDECODE  > ${LOGDIR}/sysconfig/dmidecode.out 2>&1
-  fi
-  if [ -x $LSHW  ] ; then
-    $LSHW > ${LOGDIR}/sysconfig/lshw.out 2>&1
-  fi
-  $CAT /proc/cpuinfo      > ${LOGDIR}/sysconfig/proc_cpuinfo.out     2>&1
-  $CAT /proc/meminfo      > ${LOGDIR}/sysconfig/proc_meminfo.out     2>&1
-  $CAT /proc/mdstat       > ${LOGDIR}/sysconfig/proc_mdstat.out      2>&1
-  $CAT /proc/interrupts   > ${LOGDIR}/sysconfig/proc_interrupts.out  2>&1
-  $CAT /proc/filesystem   > ${LOGDIR}/sysconfig/proc_filesystems.out 2>&1
-  $CAT /proc/devices      > ${LOGDIR}/sysconfig/proc_devices.out     2>&1
-  $CAT /proc/iomem        > ${LOGDIR}/sysconfig/proc_iomem.out       2>&1
-  $CAT /proc/ioports      > ${LOGDIR}/sysconfig/proc_ioports.out     2>&1
-  $CAT /proc/partitions   > ${LOGDIR}/sysconfig/proc_partitions.out  2>&1
-  $CAT /proc/slabinfo     > ${LOGDIR}/sysconfig/proc_slabinfo.out    2>&1
-  $CAT /proc/softirqs     > ${LOGDIR}/sysconfig/proc_softirqs.out    2>&1
-   physicalCPUs=$( $CAT /proc/cpuinfo | grep "physical id" | $SORT | $UNIQ | $WC -l )
-       cpuCores=$( $CAT /proc/cpuinfo | grep "cpu cores"  | $UNIQ  )
-  cpuProcessors=$( $CAT /proc/cpuinfo | grep "^processor" | $UNIQ  )
   echo "Physical CPU      : $physicalCPUs"  >> ${LOGDIR}/sysconfig/cpu_details.txt
   echo "CPU Cores         : $cpuCores"      >> ${LOGDIR}/sysconfig/cpu_details.txt
   echo "CPU Processors    : $cpuCores"      >> ${LOGDIR}/sysconfig/cpu_details.txt
@@ -856,12 +882,12 @@ hardware_checks() {
 boot_section() {
   Echo "Section - Boot Info"
   if [ -x "/sbin/lilo" ] ; then
-    /sbin/lilo -q   > $LOGDIR/system/lilo_-q  2>&1
+    /sbin/lilo -q   > $LOGDIR/sysconfig/lilo_-q  2>&1
   fi
-  $LS -alR /boot  > ${LOGDIR}/system/ls-alR_boot.out 2>&1
+  $LS -alR /boot  > ${LOGDIR}/sysconfig/ls-alR_boot.out 2>&1
   MakeDir ${LOGDIR}/boot/grub
   MakeDir ${LOGDIR}/patch+pkg
-  MakeDir ${LOGDIR}/system
+  MakeDir ${LOGDIR}/sysconfig
   for i in  /boot/grub/menu.lst  /boot/grub/grub.conf /boot/grub.conf /boot/grub/device.map ; do
     if [ -f ${i} ] ; then
       $CP -p ${i} ${LOGDIR}/${i}
@@ -905,19 +931,30 @@ performance_info() {
   fi
   if [ -x $IPCS ] ; then
     $IPCS -a    > ${LOGDIR}/sysconfig/ipcs_-a.out
-    $IPCS -u    > ${LOGDIR}/sysconfig/ipcs_-u.out
-    $IPCS -l    > ${LOGDIR}/sysconfig/ipcs_-l.out
+    if [ "$OSNAME" == "Darwin" ] ; then
+      $IPCS -q  > ${LOGDIR}/sysconfig/ipcs_-u.out
+      $IPCS -s  > ${LOGDIR}/sysconfig/ipcs_-l.out
+    else
+      $IPCS -u  > ${LOGDIR}/sysconfig/ipcs_-u.out
+      $IPCS -l  > ${LOGDIR}/sysconfig/ipcs_-l.out
+    fi
   fi
   $UPTIME       > ${LOGDIR}/sysconfig/uptime.out
   ulimit -a     > ${LOGDIR}/sysconfig/ulimit_-a.out
   if [ -x $VMSTAT ] ; then
-    $VMSTAT -s    > ${LOGDIR}/sysconfig/vmstat_-s.out
+    if [ "$OSNAME" == "Darwin" ] ; then
+      $VMSTAT    > ${LOGDIR}/sysconfig/vmstat_-s.out
+    else
+      $VMSTAT -s > ${LOGDIR}/sysconfig/vmstat_-s.out
+    fi
   fi
   if [ "$LSOF" != "" ] ; then
     $LSOF >  ${LOGDIR}/sysconfig/lsof.out  2>&1
   fi
   if [ -d /var/log/sa ] ; then
-    $CP -p /var/log/sa/sa*   ${LOGDIR}/var/log/sa
+    if [ "$($LS -l /var/log/sa/ |$WC -l |$SED 's/ //g')" != "0" ]  ; then
+      $CP -p /var/log/sa/sa*   ${LOGDIR}/var/log/sa
+    fi
   fi
   if [ -e /proc/loadavg ] ; then
     $CAT /proc/loadavg    > ${LOGDIR}/sysconfig/loadavg.out
@@ -954,7 +991,9 @@ kernel_info() {
   $CP -p /lib/modules/$($UNAME -r)/modules.dep ${LOGDIR}/sysconfig/modules.dep
   $MODPROBE -n -l -v  > ${LOGDIR}/sysconfig/modprobe_-n-l-v.out  2>&1
   $DEPMOD -av         > ${LOGDIR}/sysconfig/depmod_-av.out       2>&1
-  $CAT /proc/modules  > ${LOGDIR}/sysconfig/modules.out          2>&1
+  if [ -e /proc/modules ] ; then
+    $CAT /proc/modules  > ${LOGDIR}/sysconfig/modules.out        2>&1
+  fi
   ##############################################################################
   # Get the kernel configuration details from a 2.6 kernel
   ##############################################################################
@@ -985,9 +1024,11 @@ disk_info() {
   if [ -x $SWAPON ] ; then
     $SWAPON -s > ${LOGDIR}/swapon_-s.out 2>&1
   fi
-  $MOUNT            > ${LOGDIR}/disks/mount.out           2>&1
-  $MOUNT -l         > ${LOGDIR}/disks/mount_-l.out        2>&1
-  $CAT /proc/mounts > ${LOGDIR}/disks/cat_proc-mounts.out 2>&1
+  $MOUNT              > ${LOGDIR}/disks/mount.out           2>&1
+  $MOUNT -l           > ${LOGDIR}/disks/mount_-l.out        2>&1
+  if [ -f /proc/mounts ] ; then
+    $CAT /proc/mounts > ${LOGDIR}/disks/cat_proc-mounts.out 2>&1
+  fi
 
   # Display any quotas that my have been set
   if [ -x  $REPQUOTA ] ; then
@@ -1375,14 +1416,16 @@ lvm_info() {
 
 disk_dm_info() {
   Echo "Section - Disk DM Info "
-  # Work out which dm device is being used by each filesystem
-  grep dm-[0-9] /proc/diskstats | awk '{print $1, $2, $3}' | while read line ; do
-     Major=$(echo $line | awk '{print $1}' )
-     Minor=$(echo $line | awk '{print $2}' )
-    Device=$(echo $line | awk '{print $3}' )
-      List=$(ls -la /dev/mapper | grep "${Major},  ${Minor}" | awk '{print $(NF)}')
-    echo "$Device = $List " >> ${LOGDIR}/disks/dm-info.out
-  done
+  if [ -f /proc/diskstats ] ; then
+    # Work out which dm device is being used by each filesystem
+    grep dm-[0-9] /proc/diskstats | awk '{print $1, $2, $3}' | while read line ; do
+       Major=$(echo $line | awk '{print $1}' )
+       Minor=$(echo $line | awk '{print $2}' )
+      Device=$(echo $line | awk '{print $3}' )
+        List=$(ls -la /dev/mapper | grep "${Major},  ${Minor}" | awk '{print $(NF)}')
+      echo "$Device = $List " >> ${LOGDIR}/disks/dm-info.out
+    done
+  fi
 }
 
 ##############################################################################
@@ -1845,12 +1888,14 @@ network_info() {
   #
   # Collect bridging information
   #
-  if [ -x "${BRCTL}" ] ; then
-    $BRCTL show > ${LOGDIR}/network/brctl_show.out 2>&1
-    for myBridge in $($BRCTL show | grep -v "STP enabled" |  grep ^[a-zA-Z] | awk '{ print $1}') ; do
-      $BRCTL showmacs $myBridge > ${LOGDIR}/network/btctl_showmacs_${myBridge}.out 2>&1
-      $BRCTL showstp  $myBridge > ${LOGDIR}/network/btctl_showstp_${myBridge}.out 2>&1
-    done
+  if [ "$OSNAME" == "Linux" ] ; then
+    if [ -x "${BRCTL}" ] ; then
+      $BRCTL show > ${LOGDIR}/network/brctl_show.out 2>&1
+      for myBridge in $($BRCTL show | grep -v "STP enabled" |  grep ^[a-zA-Z] | awk '{ print $1}') ; do
+        $BRCTL showmacs $myBridge > ${LOGDIR}/network/btctl_showmacs_${myBridge}.out 2>&1
+        $BRCTL showstp  $myBridge > ${LOGDIR}/network/btctl_showstp_${myBridge}.out 2>&1
+      done
+    fi
   fi
 }
 
@@ -2227,7 +2272,11 @@ taritup_info() {
     exit 1
   fi
   if [ -t 0 ] ; then
-    Sum=$($MD5SUM ${TARFILE} | $AWK '{print $1}' )
+    if [ "$OSNAME" == "Darwin" ] ; then
+      Sum=$($MD5SUM -q ${TARFILE}                  )
+    else
+      Sum=$($MD5SUM ${TARFILE} | $AWK '{print $1}' )
+    fi
     echo
     echo "A support file has been created for support purposes"
     echo
@@ -2337,8 +2386,16 @@ System_Info() {
   fi
   systemPlatform=$($UNAME -m)
   kernelVersion=$($UNAME -r)
-  Mem=$(cat /proc/meminfo | grep ^MemTotal: | awk '{print $2}')
-  MEMINFO=$(echo $(($Mem / 1000000)))
+  if [ "$OSNAME" == "Darwin" ] ; then
+    MEMINFO=$(hostinfo |grep memory |cut -f2 -d: |awk '{print $1}')
+    VMSTATS=$($VMSTAT)
+    SWAPINF=$(sysctl vm.swapusage)
+  else
+    Mem=$(cat /proc/meminfo | grep ^MemTotal: | awk '{print $2}')
+    MEMINFO=$(echo $(($Mem / 1000000)))
+    VMSTATS=$($VMSTAT 2 5 | $SED '1d' | $COLUMN -t  2> /dev/null )
+    SWAPINF=$($SWAPON -s | $GREP -v "Filename")
+  fi
   if [ -x $LSB_RELEASE ] ; then
     LSB_RELEASE_INFO=$(${LSB_RELEASE} -a )
   else
@@ -2395,10 +2452,10 @@ System_Info() {
            $(${UPTIME})
 
            swapon -s:
-           $($SWAPON -s | $GREP -v "Filename")
+           $SWAPINF
 
            vmstat:
-           $($VMSTAT 2 5 | $SED '1d' | $COLUMN -t  2> /dev/null )
+           $VMSTATS
 
            df:
            $($DF -h )
@@ -2590,11 +2647,14 @@ RemoveDir ${LOGTOP}
 
 #  make sure this is a linux system
 
-if [ "$($UNAME -s)" != "Linux" ] ; then
-  echo "ERROR: This script is only for Linux systems "
-  exit 1
+if [ "$OSNAME" == "Darwin" ] ; then
+  echo "WARNING: Running on MacOS X (experimental support only)" 
+else
+  if [ "$($UNAME -s)" != "Linux" ] ; then
+    echo "ERROR: This script is only for Linux systems "
+    exit 1
+  fi
 fi
-
 
 # Make the directory I'm going to store all the files
 
